name:                hs99
version:             0.1.0.0
github:              "githubuser/codeleventh"
license:             BSD3
author:              "codeleventh"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/codeleventh/hs-99#readme>

dependencies:
- base >= 4.7 && < 5
- random
- ghci >= 8.4.1

library:
  source-dirs: src

executables:
  hs99-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs99

tests:
  hs99-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-test
